// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BindingsGen from "./Bindings.gen";

var Link = {};

var Gatsby = {
  Link: Link
};

var Helmet = {};

var faInstagram = BindingsGen.faInstagram;

var faLinkedin = BindingsGen.faLinkedin;

var faGithub = BindingsGen.faGithub;

var make = BindingsGen.FontAwesomeIcon;

var FontAwesomeIcon = {
  make: make
};

var Fontawesome = {
  faInstagram: faInstagram,
  faLinkedin: faLinkedin,
  faGithub: faGithub,
  FontAwesomeIcon: FontAwesomeIcon
};

var make$1 = BindingsGen.ArrowUpRight;

var ArrowUpRight = {
  make: make$1
};

var Feather = {
  ArrowUpRight: ArrowUpRight
};

export {
  Gatsby ,
  Helmet ,
  Fontawesome ,
  Feather ,
  
}
/* faInstagram Not a pure module */
