// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Layout$GatsbyStarterHelloWorld from "./Layout.bs.js";
import * as LayoutArticleHeader$GatsbyStarterHelloWorld from "./LayoutArticleHeader.bs.js";

import './highlight.css'
;

import './prose.css'
;

function metadata(js) {
  return {
          title: Json_decode.field("title", Json_decode.string, js),
          date: Json_decode.field("date", Json_decode.string, js),
          tags: Json_decode.withDefault([], (function (param) {
                  return Json_decode.field("tags", (function (param) {
                                return Json_decode.array(Json_decode.string, param);
                              }), param);
                }), js)
        };
}

var Decode = {
  metadata: metadata
};

function BlogLayout(Props) {
  var children = Props.children;
  var metadata$1 = Props.metadata;
  var metadata$2 = metadata(metadata$1);
  var header = React.createElement(LayoutArticleHeader$GatsbyStarterHelloWorld.make, {
        title: metadata$2.title,
        subhead: "Blog",
        date: metadata$2.date,
        tags: metadata$2.tags
      });
  return React.createElement(Layout$GatsbyStarterHelloWorld.make, {
              header: header,
              children: React.createElement("article", {
                    className: "max-w-2xl text-lg mx-auto text-gray-800 leading-relaxed prose"
                  }, React.createElement("div", undefined, children))
            });
}

var make = BlogLayout;

export {
  Decode ,
  make ,
  
}
/*  Not a pure module */
