// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Layout$GatsbyStarterHelloWorld from "./Layout.bs.js";
import * as LayoutArticleHeader$GatsbyStarterHelloWorld from "./LayoutArticleHeader.bs.js";

import './highlight.css'
;

import './prose.css'
;

function BlogLayout$default(Props) {
  var param = Props.pageContext;
  var frontmatter = param.frontmatter;
  return React.createElement(Layout$GatsbyStarterHelloWorld.make, {
              header: React.createElement(LayoutArticleHeader$GatsbyStarterHelloWorld.make, {
                    title: frontmatter.title,
                    subhead: "Blog",
                    date: frontmatter.date,
                    tags: Belt_Option.getWithDefault(frontmatter.tags, [])
                  }),
              children: React.createElement("article", {
                    className: "max-w-2xl text-lg mx-auto text-gray-800 leading-relaxed prose"
                  }, React.createElement("div", {
                        dangerouslySetInnerHTML: {
                          __html: param.html
                        }
                      }))
            });
}

var $$default = BlogLayout$default;

export {
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
