// Generated by ReScript, PLEASE EDIT WITH CARE


var link_ = "transition-all duration-200 ";

var link = link_ + " underline-gradient";

var linkDark = link_ + " underline-gradient underline-gradient-dark";

var gradient = "from-pink-700 via-pink-500 to-orange-500";

export {
  link ,
  linkDark ,
  gradient ,
  
}
/* No side effect */
