// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import AboutSection from "./AboutSection";
import * as Layout$GatsbyStarterHelloWorld from "./Layout.bs.js";
import * as IndexHeader$GatsbyStarterHelloWorld from "./IndexHeader.bs.js";
import * as CommonStyles$GatsbyStarterHelloWorld from "./CommonStyles.bs.js";

function Homepage$Section(Props) {
  var children = Props.children;
  var head = Props.head;
  return React.createElement("article", undefined, React.createElement("h2", {
                  className: "text-black font-bold mb-2"
                }, head), React.createElement("div", {
                  className: "text-gray-600"
                }, children));
}

var Section = {
  make: Homepage$Section
};

var make = AboutSection;

var AboutSectionMd = {
  make: make
};

function Homepage$AboutSection(Props) {
  return React.createElement(Homepage$Section, {
              children: React.createElement("div", {
                    className: "space-y-3"
                  }, React.createElement(make, {})),
              head: "About"
            });
}

var AboutSection$1 = {
  make: Homepage$AboutSection
};

var categories_0 = {
  label: "ui frameworks",
  children: [
    "react",
    "elm",
    "flutter",
    "lit-element"
  ]
};

var categories_1 = {
  hd: {
    label: "css",
    children: [
      "tailwind",
      "sass"
    ]
  },
  tl: {
    hd: {
      label: "design",
      children: [
        "framer",
        "adobe xd"
      ]
    },
    tl: {
      hd: {
        label: "langs",
        children: [
          "typescript",
          "reasonml",
          "haskell",
          "clojure"
        ]
      },
      tl: {
        hd: {
          label: "build tools",
          children: [
            "gatsby",
            "parcel",
            "snowpack"
          ]
        },
        tl: {
          hd: {
            label: "state management",
            children: ["redux"]
          },
          tl: {
            hd: {
              label: "coding style",
              children: ["prettier"]
            },
            tl: /* [] */0
          }
        }
      }
    }
  }
};

var categories = {
  hd: categories_0,
  tl: categories_1
};

function Homepage$ToolsSection(Props) {
  return React.createElement(Homepage$Section, {
              children: Belt_List.reduceWithIndex(categories, React.createElement(React.Fragment, undefined), (function (acc, param, index) {
                      return React.createElement(React.Fragment, undefined, acc, index === 0 ? null : " • ", React.createElement("span", {
                                      className: "whitespace-no-wrap"
                                    }, React.createElement("span", {
                                          className: "text-gray-400 font-light"
                                        }, param.label), " ", React.createElement("span", {
                                          className: "whitespace-normal"
                                        }, param.children.join(", "))));
                    })),
              head: "Selected tools and technologies"
            });
}

var ToolsSection = {
  categories: categories,
  make: Homepage$ToolsSection
};

function Homepage$ProjectsSection(Props) {
  return React.createElement(Homepage$Section, {
              children: React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                            className: CommonStyles$GatsbyStarterHelloWorld.link,
                            href: "https://studiodentisticoandreinafraioli.it"
                          }, "studiodentisticoandreinafraioli.it")), React.createElement("li", undefined, React.createElement("a", {
                            className: CommonStyles$GatsbyStarterHelloWorld.link,
                            href: "https://lambda-calculus-interpreter.netlify.app"
                          }, "online λ-calculus interpreter")), React.createElement("li", undefined, React.createElement("span", {
                            className: "text-gray-400 font-semibold"
                          }, "more coming soon..."))),
              head: "Projects"
            });
}

var ProjectsSection = {
  make: Homepage$ProjectsSection
};

function Homepage(Props) {
  return React.createElement(Layout$GatsbyStarterHelloWorld.make, {
              header: React.createElement(IndexHeader$GatsbyStarterHelloWorld.make, {}),
              children: React.createElement("main", {
                    className: "max-w-md mx-auto space-y-10 leading-relaxed"
                  }, React.createElement(Homepage$AboutSection, {}), React.createElement(Homepage$ToolsSection, {}), React.createElement(Homepage$ProjectsSection, {}))
            });
}

var make$1 = Homepage;

export {
  Section ,
  AboutSectionMd ,
  AboutSection$1 as AboutSection,
  ToolsSection ,
  ProjectsSection ,
  make$1 as make,
  
}
/* make Not a pure module */
