// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Bindings$GatsbyStarterHelloWorld from "./Bindings.bs.js";
import * as CommonStyles$GatsbyStarterHelloWorld from "./CommonStyles.bs.js";

function IndexHeader$LinkIcon(Props) {
  var href = Props.href;
  var icon = Props.icon;
  return React.createElement("div", {
              className: "cursor-pointer transition-colors duration-300 hover:bg-dark-gray flex h-12 w-12 items-center justify-center "
            }, React.createElement("a", {
                  href: href,
                  rel: "noopener noreferrer",
                  target: "__blank"
                }, React.createElement(Bindings$GatsbyStarterHelloWorld.Fontawesome.FontAwesomeIcon.make, {
                      className: "fill-current",
                      icon: icon,
                      size: "lg"
                    })));
}

var LinkIcon = {
  make: IndexHeader$LinkIcon
};

function IndexHeader(Props) {
  var keywordClass = "text-darkest-gray -mx-1 px-1 animate-gradient " + CommonStyles$GatsbyStarterHelloWorld.gradient;
  return React.createElement("div", {
              className: "max-w-md mx-auto"
            }, React.createElement("h1", {
                  className: "text-5xl font-extrabold text-white leading-snug font-serif"
                }, "Hi, I'm Alessandro.", React.createElement("br", undefined), " I ", React.createElement("span", {
                      className: "appear"
                    }, React.createElement("span", {
                          className: "bg-gradient-45 animate-gradient-a " + keywordClass
                        }, "design"), " and ", React.createElement("span", {
                          className: "bg-gradient-150 animate-gradient-b " + keywordClass
                        }, "build"), "* things.")), React.createElement("p", {
                  className: "mt-6 text-sm text-gray-200 font-light"
                }, "*Also, I usually break them"), React.createElement("div", {
                  className: "h-16"
                }), React.createElement("div", {
                  className: "text-gray-200 flex space-x-4 -ml-4"
                }, React.createElement(IndexHeader$LinkIcon, {
                      href: "https://www.linkedin.com/in/alessandro-scandone-035b241a2/",
                      icon: Bindings$GatsbyStarterHelloWorld.Fontawesome.faLinkedin
                    }), React.createElement(IndexHeader$LinkIcon, {
                      href: "https://github.com/ascandone",
                      icon: Bindings$GatsbyStarterHelloWorld.Fontawesome.faGithub
                    }), React.createElement(IndexHeader$LinkIcon, {
                      href: "https://www.instagram.com/alescandone/",
                      icon: Bindings$GatsbyStarterHelloWorld.Fontawesome.faInstagram
                    })));
}

var make = IndexHeader;

export {
  LinkIcon ,
  make ,
  
}
/* react Not a pure module */
