// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Chip$GatsbyStarterHelloWorld from "./Chip.bs.js";
import * as Link$GatsbyStarterHelloWorld from "./Link.bs.js";
import * as Bindings$GatsbyStarterHelloWorld from "./Bindings.bs.js";

function LayoutArticleHeader(Props) {
  var title = Props.title;
  var subhead = Props.subhead;
  var date = Props.date;
  var tagsOpt = Props.tags;
  var description = Props.description;
  var tags = tagsOpt !== undefined ? tagsOpt : [];
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "text-4xl font-serif font-extrabold leading-tight antialiased"
                }, React.createElement("h5", {
                      className: "text-gray-500 "
                    }, subhead), React.createElement("h2", {
                      className: "text-white"
                    }, title), React.createElement("div", {
                      className: "mt-3"
                    })), date !== undefined ? React.createElement("h6", {
                    className: "uppercase text-sm font-light tracking-wide text-gray-300"
                  }, date) : React.createElement("div", {
                    className: "mt-10"
                  }), React.createElement("div", {
                  className: "mt-4"
                }), description !== undefined ? React.createElement("p", {
                    className: "text-gray-300"
                  }, description) : null, React.createElement("div", {
                  className: "flex justify-between mt-10"
                }, tags.length === 0 ? null : React.createElement("div", {
                        className: "flex flex-wrap"
                      }, Belt_Array.mapWithIndex(tags, (function (key, tag) {
                              return React.createElement("div", {
                                          key: String(key),
                                          className: "mr-4 mb-3"
                                        }, React.createElement(Chip$GatsbyStarterHelloWorld.make, {
                                              children: tag,
                                              dark: true
                                            }));
                            }))), React.createElement("div", {
                      className: "mr-8"
                    }), React.createElement("span", {
                      className: "text-cool-gray-300"
                    }, React.createElement("span", {
                          className: "flex items-center"
                        }, React.createElement(Link$GatsbyStarterHelloWorld.make, {
                              to_: "/",
                              children: React.createElement("span", {
                                    className: "font-semibold"
                                  }, "Home"),
                              dark: true
                            }), React.createElement(Bindings$GatsbyStarterHelloWorld.Feather.ArrowUpRight.make, {
                              className: "h-5"
                            })))));
}

var make = LayoutArticleHeader;

export {
  make ,
  
}
/* react Not a pure module */
