// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ReactHelmet from "react-helmet";

import './layout.css'
;

function Layout(Props) {
  var header = Props.header;
  var children = Props.children;
  return React.createElement("div", {
              className: "bg-darkest-gray antialiased"
            }, React.createElement(ReactHelmet, {
                  children: null
                }, React.createElement("meta", {
                      content: "#121212",
                      name: "theme-color"
                    }), React.createElement("link", {
                      href: "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@800&family=Nunito:ital,wght@0,300;0,400;0,600;0,700;1,400;1,700&display=swap",
                      rel: "stylesheet"
                    }), React.createElement("title", undefined, "Alessandro Scandone :: Dev")), React.createElement("div", {
                  className: "flex flex-col md:flex-row"
                }, React.createElement("header", {
                      className: "md:flex-1 py-16 flex sm:justify-center items-center md:h-screen"
                    }, React.createElement("div", {
                          className: "md:max-w-md px-5 md:fixed w-full md:w-1/2 antialiased"
                        }, header)), React.createElement("main", {
                      className: "min-w-0 rounded-t-lg md:rounded-none flex-1 py-8 bg-white md:flex min-h-screen"
                    }, React.createElement("div", {
                          className: "max-w-full px-5 lg:px-8 xl:px-16"
                        }, children))));
}

var make = Layout;

export {
  make ,
  
}
/*  Not a pure module */
